// glossaryファイル IT
`use strict`
const glossary = [
{target:`★IT業界の動向がわかるトレンド用語`, content:`ーーーーー`},
{target:`ゼロトラスト`, content:`どの通信も信頼できない、という前提で検査する。`},
{target:`エッジコンピューティング`, content:`端末側で処理してサーバーの負荷や遅延を減らす。`},
{target:`量子コンピューティング`, content:`難問を解くことを期待されているコンピュータ。`},
{target:`DX`, content:`データやデジタル技術で企業のビジネスモデルを変革する。`},
{target:`5G`, content:`携帯電話での第5世代の無線通信技術。`},
{target:`シンギュラリティ`, content:`人工知能の能力が人間を超えるという仮説。`},
{target:`RPA（Robotic Process Automation）`, content:`事務処理などの業務を自動化する。`},
{target:`LPWA（Low Power Wide Area）`, content:`低消費電力で長距離の通信を実現した無線通信技術。`},
{target:`LTE-M（Long Term Evolution for Machine-type-communication）`, content:`LTEの空いた領域を使用するIoT通信規格。`},
{target:`NGN（Next Generation Network）`, content:`次世代のネットワーク基盤。`},
{target:`IPoE（IP over Ethernet）`, content:`LANと同じ方法でインターネットに接続する接続方式。`},
{target:`MaaS（Mobility as a Service）`, content:`ITを活用してあらゆる交通機関を統合して利用。`},
{target:`HCI（Hyper-Converged Infrastructure）`, content:`1台でシンプルなサーバー構成を実現できるインフラ製品。`},
{target:`マイクロサービス`, content:`複数の小さなサービスに分類してアプリケーションを構成。`},
{target:`ブロックチェーン`, content:`分散型ネットワークと暗号技術を使ったデータ管理手法。`},
{target:`xR（VR：Virtual Reality、AR：Augmented Reality、MR：Mixed Reality）`, content:`現実世界と仮想世界の融合。`},
{target:`LiDAR（light Detection And Ranging）`, content:`反射を利用した距離の測定。`},
{target:`オムニチャネル`, content:`ネットとリアルを融合したマーケティング手法。`},
{target:`オンプレミス`, content:`サーバーを自社で構築・運用。`},
{target:`VUI（Voice User Interface）`, content:`スマートスピーカーで広がる音声認識のインターフェイス。`},
{target:`サブスクリプション`, content:`利用料を支払って期間内だけ利用する契約。`},
{target:`NFC（Near Field Communication）`, content:`非接触のICチップで実現した近距離の無線通信。`},
{target:`フィンテック`, content:`ITと金融の融合。`},
{target:`SDGs（Sustainable Development Goals）`, content:`世界が抱える諸問題に対するゴール。`},
{target:`デジタルツイン`, content:`サイバー空間上に物理空間を再現する。`},
{target:`eSIM（embedded Subscriber Identity Module）`, content:`交換せずにキャリアや通信プランを変更できるSIM。`},
{target:`GIGAスクール構想（Global and Innovation Gateway for All）`, content:`学校におけるICTの活用。`},
{target:`データサイエンティスト`, content:`ビックデータやAIを活用してデータから知見を得る人。`},
{target:`レコメンデーション`, content:`顧客に合わせた商品やサービスをおすすめ。`},
{target:`ダイナミックプライシング`, content:`需要と共有に合わせて値段を変動させる。`},
{target:`ノーコードとローコード`, content:`最小限のコーディングでソフトウェアを開発。`},
{target:`OTG（USB On-The-Go）`, content:`スマホとUSB機器を直接接続できる企画。`},
{target:`STEM教育とSTEAM教育（Science, Technology, Engineering (,Art) and Mathematics）`, content:`理数教育に創造性教育を加えた教育概念。`},
{target:`ドッグフーディング`, content:`社内で自社の製品を使ってテストする。`},
{target:`★エンジニア1年目から知っておきたい基本用語`, content:`ーーーーー`},
{target:`GDPR（General Data Protection Regulation）`, content:`EUにおける個人情報保護の枠組み。`},
{target:`CCPA（Califolnia Consumer Privacy Act）`, content:`カリフォルニア州における個人情報保護の枠組み。`},
{target:`CxO（CTO,CIO,CISO,…）（Chief xxx Officer）`, content:`企業における様々な責任者の総称と呼称。`},
{target:`VPoE（Vice President of Engineering）`, content:`エンジニアを率いるマネジメント責任者。`},
{target:`テックリード`, content:`技術面でチームを引っ張り、他チームと連携する。`},
{target:`EM（Engineering Manager）`, content:`エンジニアの技術力や働き方を最大化する。`},
{target:`フルスタック`, content:`1人で幅広い領域の技術を網羅。`},
{target:`1 on 1`, content:`部下の成長をサポートする定期的なミーティング。`},
{target:`OKR（Objectives and Key Results）`, content:`会社の目標と個人の目標を連携させるフレームワーク。`},
{target:`MBO（Management by Objectives）`, content:`目標管理の方法。上司と部下で目標設定し、半年や1年間での達成度を評価。`},
{target:`SMART（Specific, Measurable, Achievable, Relevant, Time-based）`, content:`目標設定の5要素。具体的、測定可能、達成可能、経営目標に関連し、時間制約がある指標のこと。`},
{target:`情報銀行`, content:`行動履歴や購買履歴を一元管理。`},
{target:`オプトイン`, content:`本人の同意を事前に得ること。`},
{target:`オプトアウト`, content:`本人の同意を事前に得ないこと。`},
{target:`Society 5.0`, content:`IoTで新たな価値を産みだし、課題や困難を克服。`},
{target:`コネクティッドシティ`, content:`最先端技術で作る未来都市。`},
{target:`スマートグリッド`, content:`ITを使いエネルギーの需要を測定し、必要なところに効率よく送電する仕組み。`},
{target:`スマートメータ―`, content:`電力やガス、水道の使用量を測定する機能に加え、通信機能により電力会社などに検針結果やリアルタイムの使用量などを送信できる。`},
{target:`スマートホーム`, content:`AiやIoTの技術を使って設備を便利に利用できる住宅のこと。`},
{target:`ギグエコノミー`, content:`インターネット経由で一時的な仕事を受ける新しい働き方。`},
{target:`クラウドソーシング`, content:`ネットなどで個人や企業をマッチングし仕事の発注や受注を行う仕組み。`},
{target:`シェアリングエコノミー`, content:`ネットを通して個人をマッチングし、モノや場所、ｽｷﾙ、お金、時間などを必要な時に必要なだけ個人間で共有する社会やサービスのこと。`},
{target:`インダストリー4.0`, content:`製造業における新たな産業革命。AiやIoTによる高度な自働化のこと。スマートファクトリーとも呼ばれ、より効率よく製造できる。`},
{target:`セル生産`, content:`1つの製品を少人数で組み立てる方式で、仕様変更にも柔軟に対応でき、少量多品種の生産が可能。`},
{target:`ダイナミックセル生産`, content:`リアルタイムに変化する情報をネット経由でロボットが取得し、その情報に応じて生産する方式で、ライン生産とセル生産の良いところを組合せている。`},
{target:`PoC（Proof of Concept）`, content:`新しいアイデアを試して投資判断に役立てる。概念実証。新しい技術やアイデアなどを実際に試してみることを指す。製品やシステムの簡易版を作ってみて、その実現可能性や社会での需要などを位定めるために実施される。`},
{target:`パイロットプロジェクト`, content:`一部の部署、利用者だけを対象として試験的に実施されるプロジェクトのこと。`},
{target:`PoT（Proof of Technology）`, content:`技術実証。技術的な課題の有無を検証するために実施される。ビジネス的より、技術的な視点であり、実現可否を調べること。`},
{target:`R＆D（Research and Development）`, content:`研究開発。`},
{target:`PLM（Product Lifecycle Management）`, content:`製品の企画から廃棄までを管理する手法。`},
{target:`BPMとBPMS（Business Process Management (Suite/System)）`, content:`企業の業務改善を可視化。仕事を進める上での手順や役割分担、ルールなどを関係者の間で共有し、その業務の流れにおける問題点などの分析や最適化を継続的に繰り返して改善すること。ITツールを使ってリアルタイムで可視化し、対策を実施するツールや、単純にツールを導入するだけでなく、戦略的に業務を改善・改革する活動をさす。`},
{target:`BRMS（Business Rule Management System）`, content:`実務におけるルールを管理してシステム開発を効率化。組織などにおけるビジネスのルールをルールエンジンと呼ばれる場所に登録して管理する手法。`},
{target:`ナレッジマネジメント`, content:`従業員の持つ知識を組織の内部で蓄積、共有し、組織として活用する試みのこと。専用のシステムが導入されることもある。`},
{target:`DMN（Decition Model and Notation）`, content:`BPMNの中で意思決定に関する部分を表現するための表記法。意思決定に必要な情報、知識、根拠などを図で書くことで共通認識を持つために使われる。`},
{target:`ERP（Enterprise Resources Planning）`, content:`企業の基幹システムで全体を最適化。組織運営に必要なヒト・モノ・カネ・情報の資源を有効に活用するため、組織が持つ情報を一元管理して経営戦略や戦術を決定するための考え方のこと。`},
{target:`SCM（Supply Cahin Management）`, content:`受注から納品までを一元管理。`},
{target:`CRM（Customer Relationship Management）`, content:`顧客情報を管理して顧客に合った商品やサービスを提供。顧客とのやり取りを記録・分析し、業務に活かす手法や、そのためのツールのこと。`},
{target:`インサイドセールス`, content:`営業担当者が、電話やメールなどを使って顧客とコミュニケーションをとる営業方法。`},
{target:`リードジェネレーション`, content:`見込み顧客獲得のこと。展示会での名刺交換やセミナーの開催、Webサイトの問合せフォームからの資料請求など。`},
{target:`リードナーチャリング`, content:`見込み顧客に対して情報の提供や問い合わせ対応を通して自社の顧客になってもらうこと。`},
{target:`SFA（Sales Force Automation）`, content:`企業の営業活動に関するデータを一元管理。営業の自働化と訳され、営業担当者の日々の活動を入力することで、組織として顧客情報や進捗状況、売上の集計などが可能なシステムのことを指し、営業支援システムとも呼ばれる。`},
{target:`チャットボット`, content:`人工知能を使って顧客の問い合わせ対応を自働化。`},
{target:`DSPとSSP（Demand Side Platform, Supply Side Platform）`, content:`Webにおける広告配信を最適化。Webサイトに表示される広告について、広告を表示する側と配信する側のそれぞれの利益を最大化する仕組みやツールのこと。前者は、広告主や広告代理店といった広告配信側のプラットフォームでより安く表示できる配信先を探す。後者は、広告を表示するWebサイトなど媒体側のプラットフォームでより高額な広告を探して入札する。`},
{target:`RTB（Real Time Bidding）`, content:`リアルタイム入札。Webｻｲﾄの広告を表示する時、リアルタイムにオークション形式でマッチングし、最も高い金額を付けた広告を表示する方式。`},
{target:`アドネットワーク`, content:`複数のWebサイトを取りまとめた広告ネットワーク。DSPは複数のアドネットワークに配信できる。`},
{target:`アドエクスチェンジ`, content:`アドナっとワークが持つ広告枠を交換し、自由に売買する仕組み。`},
{target:`RFID（Radio Frequency IDentification）`, content:`ID情報を埋め込んだタグで商品などを管理。NFCと比べて通信距離が長い特徴がある。`},
{target:`パッシブタグ`, content:`電池などの電源が内蔵されておらず、読み書きする機器からの電力を使用して電波を発信するタグ。通信距離は短いが、安価で半永久的に使用できる。`},
{target:`アクティブタグ`, content:`電池を内蔵しているため自ら電波を発信でき、長距離（数十から数百m）でも通信できるタグ。人や物の位置をリアルタイムに把握するために使われる。`},
{target:`NFC（Near Field Communication）`, content:`RFIDに近いもの。1枚100円程度で購入できる。スマホでも読み書きが可能で、読み取った時に様々な処理を実行できる。`},
{target:`アプライアンス`, content:`特定の機能に特化した機器。`},
{target:`DMP（Data Management Platform）`, content:`情報を蓄積し、顧客に合わせて広告を配信する。過去に自社のサイトで商品を購入した顧客に対して広告を配信するなど、顧客に合わせたマーケティングを実現するために使われる。DSPやSSPのマッチングの精度を高めるためにもつかわれる。`},
{target:`アドテク`, content:`広告の配信をシステム化し、効率よく調整すること。`},
{target:`KPIとKGI（Key Performance Indicator, Key Goal Indicator）`, content:`企業や部署における目標達成の指標。前者は、重要業績評価指標でページビューやコンバージョン率などの数値目標を指す。後者は、重要目標達成指標で売上高や利益率などの目標を指す。`},
{target:`コンバージョン率`, content:`Webサイトのアクセス数のうち、利用者に取ってもらいたい行動が実施された割合。`},
{target:`チャーンレート`, content:`サブスクリプションの解約率。`},
{target:`ネガティブチャーン`, content:`解約による収益の減少よりも、高額な契約などに変更した利用者などの収益がうわまわったこと。単価を上げた場合などに発生し、経営状況としては悪くない。`},
{target:`カスタマーサクセス`, content:`自社製品を使った顧客の成功のこと。継続して成功してもらえるよう積極的に支援する。`},
{target:`LTV（Life Time Value）`, content:`顧客生涯価値。顧客がその企業にもたらす価値の合計を意味する。`},
{target:`MRRとARR（Monthly Recirromg Revenue, Annual Recurring Revenue）`, content:`サブスクリプション型のビジネスの成長を調べる指標。前者は、月次経常収益でサブスクリプション型のサービスなどで毎月同じように発生する収益や売り上げのこと。単発で発生する売り上げなどは含まない。後者は、年次経常収益で前者を12倍した値だが年間契約が多いビジネスでよく使われる。`},
{target:`ARPU（Average Revenue Per User）`, content:`ユーザー平均単価。MRRを利用者の数で割った値。`},
{target:`ARPPU（Average Revenue Per Paid User）`, content:`課金ユーザー平均単価。MRRを課金している利用者の数で割った値。`},
{target:`CAC（Customer Acquisition Cost）`, content:`顧客獲得費用。顧客獲得に要した費用と獲得した顧客数で割った値。`},
{target:`アジリティ`, content:`社会の変化に追随できる機敏性。`},
{target:`EMS（Electronics Manufacturing Service）`, content:`製造業におけるアウトソーシング。電子機器の製造を請け負うメーカーのこと。生産だけでなく、設計や部品の調達、組み立て、配送まで、一気通貫で対応する。発注元は製品の企画や販売などに注力でき、工場や人件費などのコストを削減できる。`},
{target:`OEM（Original Equipment Manufacturing）`, content:`製造メーカーが自社のブランドではなく他社のブランドで製品を作ること。コスト削減や生産効率向上のために、発注元が自社で生産しないことを意味する。`},
{target:`ODM（Original Design Manufacturing）`, content:`製品の設計から製品開発までを受託者が行うこと。発注側の技術力が低い場合などに、設計も含め依頼することで、ノウハウや技術力が無くても参入できる。`},
{target:`BPO（Business Process Outsourcing）`, content:`企業の内部管理部門である総務や人事、給与計算などの業務をアウトソーシングすること。企業が本来の業務に集中するために使われることが多い。`},
{target:`Markdown`, content:`手軽に文書の構造を指定できる記法。見出しや強調、箇条書きなど文書の構造を表現する時に、簡単な指定で手軽に記述できる記法のこと。`},
{target:`ミドルウェア`, content:`OSとアプリの橋渡しをするソフトウェア。OSとアプリケーションソフトの間で、高度なサービスや機能を提供するソフトウェア。Webサーバーやデータベースサーバーなどが該当し、単独では利用されない。データベースを個々のアプリケーションソフトで実装するのは大変だが、アプリケーションが利用することで簡単にデータベースの機能を実現できる。`},
{target:`DBMS（Database Management System）`, content:`データベース管理システム。`},
{target:`Webサーバー`, content:`WebブラウザなどとHTTPと呼ばれるプロトコルでやり取りし、HTMLファイルや画像ファイルなどを提供するコンピュータやソフトウェアのこと。`},
{target:`アプリケーションサーバー`, content:`Webアプリで動的に処理を変える場合など、Webサーバー上でアプリケーションを実行するためのソフトウェアのこと。実行した結果をWebサーバーに返す。`},
{target:`デバイスドライバ`, content:`ハードウェアを操作するソフトウェア。`},
{target:`ベンチマーク`, content:`ハードウェアやソフトウェアの性能を評価する基準。`},
{target:`アドベントカレンダー`, content:`12月にエンジニアが投稿するブログのバトン。`},
{target:`形態素解析`, content:`意味のある最小限の単語などに分割して品詞を分析。`},
{target:`正規化`, content:`データの規則性に注目して整理。`},
{target:`正規表現`, content:`複数の文字列を1つのパターンで識別する表現。`},
{target:`トラフィック`, content:`一定期間内にネットワーク上を通過するデータ量。`},
{target:`トリガー`, content:`動作を開始するきっかけ。`},
{target:`★システム開発や実行環境の構築で使われるIT用語`, content:`ーーーーー`},
{target:`Docker`, content:`コンテナ型の仮想化プラットフォーム。`},
{target:`Kubernetes`, content:`コンテナ単位でアプリを自動的に管理する基盤。`},
{target:`WSL`, content:`Windows上でLinuxをネイティブに実行する仮想環境。`},
{target:`スケーラビリティ`, content:`負荷に応じてシステムを拡張。`},
{target:`ハイパーバイザー`, content:`仮想化環境を構築するための制御ソフトウェア。`},
{target:`シンプロビジョニング`, content:`ストレージを仮想化して大容量を扱えるようにする。`},
{target:`リファクタリング`, content:`外部から見た動作を変えずに内部構造を洗練。`},
{target:`ガーベジコレクション`, content:`不要になったメモリ領域を解放する機能。`},
{target:`アジャイル`, content:`要件定義からリリースまでを短期間に繰り返す手法。`},
{target:`スクラム`, content:`優先順位が高いものから動くソフトウェアを作る。`},
{target:`スパイラル`, content:`設計とプロトタイプの作成を繰り返す開発手法。`},
{target:`イテレーションとスプリント`, content:`アジャイル開発での開発サイクル。`},
{target:`リーンスタートアップ`, content:`無駄なく意思決定するために仮説検証を繰り返す手法。`},
{target:`ビルド（ビルドツール）`, content:`ソースコードから実行ファイルを生成。`},
{target:`デプロイ`, content:`開発したソフトウェアを使えるように配慮。`},
{target:`テスト駆動開発（TDD）`, content:`テストコードを事前に用意して開発を進める手法。`},
{target:`WBS`, content:`タスクを細分化して木構造に整形。`},
{target:`UML`, content:`オブジェクト指向分析・設計のための記法。`},
{target:`ドメイン駆動設計（DDD）`, content:`顧客と開発者が共通の言葉を使って設計する手法。`},
{target:`クリーンアーキテクチャ`, content:`部品の依存を一方向にするソフトウェアの設計手法。`},
{target:`CI/CD`, content:`ソフトウェアの開発プロセスを自働化。`},
{target:`RFP`, content:`ソフトウェアで実現する範囲を文書で決定。`},
{target:`IaC`, content:`インフラの構成をコードで記述。`},
{target:`FPGA`, content:`自由に書き換えられる集積回路。`},
{target:`アーキテクチャ`, content:`ハードウェアやソフトウェアの設計思想。`},
{target:`デザインパターン`, content:`ソフトウェアの設計ノウハウ集。`},
{target:`フレームワーク`, content:`多くのソフトウェアで使われる土台。`},
{target:`スレッドとプロセス`, content:`ソフトウェアがCPUを利用する単位。`},
{target:`イミュータブル`, content:`後で状態を変えられないもの。`},
{target:`オープンソース（OSS）`, content:`ソースコードが無料で公開されているソフトウェア。`},
{target:`DevOps`, content:`開発から保守まで一貫して対応。`},
{target:`SRE`, content:`信頼性を高めるため自働化などにも取り組むインフラ担当者。`},
{target:`SoEとSoR`, content:`システム設計の方向性。`},
{target:`クラスタ`, content:`多くのコンピュータの集まり。`},
{target:`マイグレーション`, content:`異なる環境への移行。`},
{target:`クロスプラットフォーム`, content:`異なる環境でも動かせるように開発。`},
{target:`ハッカソン`, content:`開発に没頭するイベント。`},
{target:`静的解析`, content:`プログラムを実行せずにチェックする手法。`},
{target:`カバレッジ`, content:`テストの網羅率を測定する時の指標。`},
{target:`NoSQL`, content:`開発データベース以外のデータベース。`},
{target:`ストアドプロシージャ`, content:`データベース内に格納される定型処理。`},
{target:`マテリアライズドビュー`, content:`データベースの参照性能を向上するための手法。`},
{target:`バージョン管理システム`, content:`ファイルの変更箇所を管理するソフトウェア。`},
{target:`★Web制作・運用で使われるIT用語`, content:`ーーーーー`},
{target:`AMP`, content:`スマホでの表示を高速化する手法。`},
{target:`OGP`, content:`WebサイトをSNSでシェアした時の表示の工夫。`},
{target:`SPA`, content:`単一のWebページでコンテンツを切り替える仕組み。`},
{target:`静的サイトジェネレータ（SSG）`, content:`MarkdownからWebサイトを生成するソフトウェア。`},
{target:`SSRとCSR`, content:`JavaScriptのコートをレンダリングする場所の違い。`},
{target:`サードパーティCookie`, content:`異なるドメインで使われるCookie。`},
{target:`ブラックハットSEO`, content:`悪質な手法で検索結果を変える。`},
{target:`レスポンシブデザイン`, content:`異なるサイズの画面でも見やすく配置するデザイン。`},
{target:`カルーセル`, content:`ページ内の要素を左右に移動して切り替える手法。`},
{target:`CSSフレームワーク`, content:`典型的なWebデザインの土台。`},
{target:`WebAssembly（WASM）`, content:`Webブラウザ上で高速に実行するプログラミング言語。`},
{target:`WebSocket`, content:`Webで双方向通信を実現する仕組み。`},
{target:`WebRTC`, content:`Webでリアルタイムな通信を実現する仕組み。`},
{target:`WebGL`, content:`Webブラウザで3Dを表示する仕組み。`},
{target:`SVG`, content:`ベクター形式で作成する画像フォーマット。`},
{target:`wepack`, content:`JavaScriptなど複数のファイルをまとめるツール。`},
{target:`WebP`, content:`圧縮率の高い新たな画像保存形式。`},
{target:`RFC`, content:`Web技術に関する仕様の提案や結果についての文書。`},
{target:`リバースプロキシ`, content:`外部から処理を仲介するサーバー機能。`},
{target:`CDN`, content:`多くのコンテンツを効率よく配信する仕組み。`},
{target:`サーバーレス`, content:`サーバーの保守や運用なしに利用する手法。`},
{target:`ヘッドレスCMS`, content:`見た目を自由に作れるWebコンテンツ管理の仕組み。`},
{target:`トランスパイラ`, content:`他のプログラミング言語のソースコードを生成。`},
{target:`JAMstack`, content:`JavaScriptとAPIで動的なWebサイトを実現する手法。`},
{target:`仮想DOM`, content:`ブラウザ内の要素を簡単に操作し高速表示する仕組み。`},
{target:`マテリアルデザイン`, content:`Googleが提唱するデザインの考え方。`},
{target:`PWA`, content:`スマホアプリのように扱えるWebアプリ。`},
{target:`Service Worker`, content:`Webページの裏側で動くスクリプト。`},
{target:`VPS`, content:`レンタルで自由に使える仮想的な専用サーバー。`},
{target:`XaaS（SaaS、PaaS、IaaS）`, content:`クラウドで提供されるサービスの形態。`},
{target:`スクレイピングとクローリング`, content:`Webサイトを巡回して抽出。`},
{target:`REST`, content:`URIを指定してリソースを操作する仕組み。`},
{target:`SOAP`, content:`Webサービス間でのデータ交換プロトコル。`},
{target:`GraphQL`, content:`WebAPI向けのクエリ言語。`},
{target:`OpenAPI（Swagger）`, content:`REST APIを定義するツール。`},
{target:`SAML`, content:`異なるドメインでのID連携の企画。`},
{target:`スクラッチ開発`, content:`ゼロから作る開発手法。`},
{target:`リファラー`, content:`アクセス先に提供されるアクセス元の情報。`},
{target:`★攻撃から守るセキュリティ・ネットワーク用語`, content:`ーーーーー`},
{target:`CIA（気密性、完全性、可用性）`, content:`セキュリティの3要素。`},
{target:`PCI DSS`, content:`クレジットカード情報を扱う時のセキュリティ基準。`},
{target:`SLA`, content:`サービス事業者が示す品質の保証内容。`},
{target:`二段階認証と多要素認証`, content:`パスワードの漏洩による不正ログインを防ぐ方法。`},
{target:`シングルサイオン（SSO）`, content:`1度のログインで複数のサービスを使う。`},
{target:`OAuth`, content:`部分的な情報にだけアクセスを許可する仕組み。`},
{target:`OpenID Connect`, content:`ログインなどの認証処理を外部に任せる仕組み。`},
{target:`FIDOとTPM`, content:`パスワードに代わる認証の規格。`},
{target:`トラッキングとITP`, content:`Web上での人の行動を追跡。`},
{target:`ワンタイムパスワード（OTP）`, content:`一定の時間で変わるパスワード。`},
{target:`WPS`, content:`無線LANを簡単に設定する仕組みや規格。`},
{target:`Wi-Fi 6`, content:`高速・多数同時接続を実現した次世代Wi-Fi。`},
{target:`インシデント`, content:`重大な事故・事件につながりかねない事案。`},
{target:`CSIRTとSOC`, content:`セキュリティに対応する組織。`},
{target:`CVSS`, content:`脆弱性の深刻さの共通基準。`},
{target:`脆弱性診断`, content:`脆弱性の存在を調べる調査。`},
{target:`UTM`, content:`複数のセキュリティ機能をまとめた機器。`},
{target:`SIEM`, content:`セキュリティに関するログを一元管理する仕組み。`},
{target:`SOAR`, content:`セキュリティの運用を自働化するシステム。`},
{target:`レピュテーション`, content:`過去の評判データを使い、悪質なものを排除する手法。`},
{target:`遠隔操作ウイルスとRAT`, content:`パソコンやスマホに感染して外部から操作。`},
{target:`ビジネスメール詐欺（BEC）`, content:`取引先になりすまし、金銭的な被害を与える手法。`},
{target:`EPP`, content:`組織内に侵入したマルウェアを検知するソフトウェア。`},
{target:`サンドボックス`, content:`保護された領域でプログラムを試すソフトウェア。`},
{target:`NGAV`, content:`AIなどを用いてマルウェアを検知するソフトウェア。`},
{target:`EDR`, content:`マルウェアの脅威を検知し、対応を支援するツール。`},
{target:`VPN`, content:`安全なネットワークを仮想的に構築する手法。`},
{target:`VDI`, content:`リモートで使うデスクトップ環境を実現する仕組み。`},
{target:`WAF`, content:`典型的な脆弱性を狙った攻撃を阻止する仕組み。`},
{target:`DLP`, content:`機密情報の外部への流出を阻止する技術。`},
{target:`SQLインジェクション`, content:`データベースを扱うアプリケーションの脆弱性。`},
{target:`XSS`, content:`複数のサイトを横断する攻撃。`},
{target:`CSRF`, content:`他人に成りすました攻撃。`},
{target:`SDNとNFV`, content:`仮想的なネットワークを実現。`},
{target:`DNSSEC`, content:`ネームサーバーからの応答を検証する手法。`},
{target:`MPLS`, content:`ラベルを使って転送先を制御する方法。`},
{target:`BLE`, content:`Bluetoothを使った低消費電力の通信。`},
{target:`PLC`, content:`コンセントにさしてインターネットに接続。`},
{target:`VoIP`, content:`インターネット経由での音声通信。`},
{target:`FQDN`, content:`URLなどでドメイン名を省略しない表記方法。`},
{target:`SSL/TLS`, content:`Webにおけるデータを暗号化する仕組み。`},
{target:`PKI`, content:`公開鍵暗号を使用したセキュリティ基盤。`},
{target:`★人工知能に使われる技術用語`, content:`ーーーーー`},
{target:`クラスタリング`, content:`似たデータを集めてグループ分け。`},
{target:`決定木`, content:`条件を木構造で表現し、分類や回帰を実現する手法。`},
{target:`ランダムフォレスト`, content:`複数の決定木による多数決で精度を高める手法。`},
{target:`サポートベクターマシン`, content:`データを分離する境界からの距離を最大化する手法。`},
{target:`ニューラルネットワーク`, content:`脳を模倣した構造で信号を伝えて計算する手法。`},
{target:`ディープラーニング（DL）`, content:`深い階層を実現したニューラルネットワーク。`},
{target:`機械学習（ML）`, content:`データをもとに気海外ルールを学習する方法。`},
{target:`教師あり学習`, content:`与えられた正解データに近づけるような学習方法。`},
{target:`教師なし学習`, content:`大量のデータから共通点を見つけて分類する学習方法。`},
{target:`強化学習`, content:`良い結果に報酬を与えて徐々に成長させる学習方法。`},
{target:`遺伝的アルゴリズム`, content:`生物の進化を模倣したアルゴリズム。`},
{target:`自己組織化マップ`, content:`近くにあるﾃﾞｰﾀを強く学習する方法。`},
{target:`転移学習`, content:`他の領域での成果を活用する効率的な学習方法。`},
{target:`MNIST`, content:`機械学習に便利な手書き数字のデータの集まり。`},
{target:`Kaggle`, content:`投稿された研究用のデータで分析を競う。`},
{target:`活性化関数`, content:`入力を変換する非線形な関数。`},
{target:`ハイパーパラメータ`, content:`機械学習の処理を調整する特別な値。`},
{target:`ヒューリスティックス`, content:`経験による勘を使って予測する手法。`},
{target:`パラメトリック`, content:`事前に母集団の分布がわかっているときに使える手法。`},
{target:`CNN`, content:`画像認識に役立つニューラルネットワーク。`},
{target:`RNN`, content:`時系列データに役立つ再帰的なニューラルネットワーク。`},
{target:`LSTM`, content:`長期記憶と短期記憶を組み合わせて学習する方法。`},
{target:`GAN（GANs）`, content:`他のAIに偽物だと判断されないものを作り出す方法。`},
{target:`ASICとTPU`, content:`特定の用途に特化した集積回路。`},
{target:`GPGPU`, content:`画像処理以外にもGPUを活用。`},
{target:`DSP`, content:`音声などの解析を高速に実行するマイクロプロセッサ。`},
{target:`マルチエージェント`, content:`複数のエージェントが協調して答えを出す方法。`},
{target:`エッジAI`, content:`現場で動く機器でAIを動かす。`},
{target:`ディープフェイク`, content:`人工知能による偽物生成技術。`},
{target:`スパースモデリング`, content:`諸横領のデータでも特徴の抽出により分析できる手法。`},
{target:`AutoML`, content:`自動的に機械学習のモデルを作成。`},
{target:`自然言語処理`, content:`人間の言葉を機械で処理する技術。`},
{target:`★使いだしたら一人前！　ITギョウカイ用語`, content:`ーーーーー`},
{target:`上げる`, content:`サーバーなどを起動する・アップロードする。`},
{target:`生きている`, content:`動作している状態。`},
{target:`枯れる`, content:`時間が経って問題点が少なくなる。`},
{target:`怒られる`, content:`警告やエラーが表示される。`},
{target:`落ちる`, content:`サーバーなどが停止する。`},
{target:`落とす`, content:`サーバーなどを終了する・ダウンロードする。`},
{target:`固まる`, content:`反応が無くなる。`},
{target:`キックする`, content:`コマンドを実行する。`},
{target:`フォークする`, content:`分岐する。`},
{target:`切る`, content:`領域を分ける、チケットを発行する。`},
{target:`食う`, content:`占有する。`},
{target:`こける`, content:`処理が失敗する。`},
{target:`殺す`, content:`制御できない処理を終了する、無効化する。`},
{target:`死ぬ`, content:`サーバーなどが停止する。`},
{target:`叩く`, content:`コマンドを実行する。`},
{target:`流す`, content:`複数の処理を実行する。`},
{target:`投げる`, content:`データを送信する。`},
{target:`なめる`, content:`一覧を順に処理する。`},
{target:`握り潰す`, content:`エラーを見ないようにする。`},
{target:`吐く`, content:`データを出力する。`},
{target:`走る`, content:`処理が実行される。`},
{target:`張り付く`, content:`使用率が高い状態が続く。`},
{target:`立てる`, content:`サーバーなどを構築する。`},
{target:`技術的には可能です`, content:`膨大なお金と時間がかかる、面倒なのでやりたくない。`},
{target:`完全に理解した`, content:`わかったつもりになっている。`},
]
